services:
        fastapi:
                build:
                        context: ./backend
                        dockerfile: Dockerfile
                container_name: backend
                ports:
                        - "8008:8000"
                depends_on:
                        - mongodb
                environment:
                        - MONGO_URI=mongodb://user:Temp@mongodb:27017/?authSource=admin
                        - MONGO_DB=undox
                volumes:
                        - ./backend:/app

        mongodb:
                image: mongo:latest
                container_name: mongodb
                restart: unless-stopped
                ports:
                        - "27018:27017"
                environment:
                        - MONGO_INITDB_ROOT_USERNAME=user
                        - MONGO_INITDB_ROOT_PASSWORD=usernumber1
                        - MONGO_INITDB_DATABASE=Temp
                volumes:
                        - ./database:/data/db
                tty: true
